name: Code Scan

on:
  push:
    branches: [main]

jobs:
  code-scan:
  
    runs-on:ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12,3.13,3.14]

    steps:

      - name: Checkout code  
        uses: actions/checkout@v4

      - name: Setup python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install linter flake 8
        run : pip install flake8

      - name: Run linter flake 8
        run: flake8 app.py
